'use client';

import { useState } from 'react';
import { CreditCard, Fingerprint, ScanFace, SmartphoneNfc, PlugZap } from 'lucide-react';
import { api, ApiError } from '../../lib/api';
import { MembershipCard } from './membership-card';
import { Input } from './input';
import { Button } from './button';
import { Badge } from './badge';

interface Device { id: string; name: string; type: string; vendor?: string | null; model?: string | null; serialNumber?: string | null; apiKeyLast4: string; status: string; lastSeenAt?: string | null; }
const TYPES = [{ value: 'CARD', label: 'کارت', icon: CreditCard }, { value: 'FINGERPRINT', label: 'اثر انگشت', icon: Fingerprint }, { value: 'FACE_RECOGNITION', label: 'تشخیص چهره', icon: ScanFace }, { value: 'NFC_PHONE', label: 'NFC گوشی', icon: SmartphoneNfc }];

export function AttendanceDevicesManager({ initial }: { initial: Device[] }) {
  const [devices, setDevices] = useState(initial); const [secret, setSecret] = useState<string | null>(null);
  const [form, setForm] = useState({ name: '', type: 'CARD', vendor: '', model: '', serialNumber: '' }); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function create(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const created = await api.post<Device & { apiKey: string }>('/attendance-devices', form); setDevices((current) => [created, ...current]); setSecret(created.apiKey); setForm({ ...form, name: '', vendor: '', model: '', serialNumber: '' }); } catch (err) { setError(err instanceof ApiError ? err.message : 'ثبت دستگاه انجام نشد.'); } finally { setLoading(false); } }
  return <div className="flex flex-col gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{TYPES.map(({ value, label, icon: Icon }) => <MembershipCard key={value}><Icon className="mb-3 size-6 text-accent-soft" /><p className="font-bold">{label}</p><p className="mt-1 text-xs leading-5 text-muted">اتصال امن از طریق شناسه دستگاه و وب‌سرویس حضور</p></MembershipCard>)}</div><div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><MembershipCard><h2 className="font-extrabold">معرفی دستگاه جدید</h2><p className="mb-5 mt-1 text-sm leading-6 text-muted">پس از ثبت، کلید اتصال فقط یک‌بار نمایش داده می‌شود.</p><form onSubmit={create} className="flex flex-col gap-3"><Input label="نام دستگاه" placeholder="مثلاً گیت ورودی بانوان" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><label className="flex flex-col gap-1.5 text-sm text-muted">نوع دستگاه<select className="h-11 rounded-xl border border-border/10 bg-surface px-3 text-ink" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{TYPES.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><Input label="سازنده" value={form.vendor} onChange={(e) => setForm({ ...form, vendor: e.target.value })} /><Input label="مدل" value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /><Input label="شماره سریال" value={form.serialNumber} onChange={(e) => setForm({ ...form, serialNumber: e.target.value })} />{error && <p className="text-sm text-danger">{error}</p>}<Button type="submit" disabled={loading}><PlugZap className="size-4" />{loading ? 'در حال ثبت…' : 'ساخت اتصال'}</Button></form>{secret && <div className="mt-5 rounded-xl border border-warning/20 bg-warning/10 p-3"><p className="text-xs font-bold text-warning">این کلید را اکنون در نرم‌افزار دستگاه ذخیره کنید:</p><code dir="ltr" className="mt-2 block break-all text-left text-xs text-ink">{secret}</code></div>}</MembershipCard><div className="flex flex-col gap-3">{devices.map((device) => <MembershipCard key={device.id}><div className="flex items-start justify-between"><div><p className="font-bold">{device.name}</p><p className="mt-1 text-sm text-muted">{TYPES.find((item) => item.value === device.type)?.label}{device.vendor ? ` · ${device.vendor}` : ''}{device.model ? ` ${device.model}` : ''}</p></div><Badge tone={device.status === 'CONNECTED' ? 'success' : 'warning'}>{device.status === 'CONNECTED' ? 'متصل' : 'در انتظار اتصال'}</Badge></div><div className="mt-4 flex flex-wrap gap-3 text-xs text-muted"><span>کلید: ••••{device.apiKeyLast4}</span>{device.serialNumber && <span>سریال: {device.serialNumber}</span>}</div></MembershipCard>)}<MembershipCard className="border-accent/20 bg-accent/5 text-sm leading-6"><strong>حریم خصوصی داده‌های زیستی:</strong> تصویر چهره یا الگوی اثر انگشت وارد سامانه نمی‌شود. دستگاه فقط یک شناسه ناشناس و رمزنگاری‌شده برای ثبت تردد ارسال می‌کند.</MembershipCard></div></div></div>;
}
