'use client';

import { useState } from 'react';
import { api, ApiError } from '../../lib/api';
import { IRAN_LOCATIONS, IRAN_PROVINCES } from '../../lib/iran-locations';
import { MembershipCard } from './membership-card';
import { Input } from './input';
import { Button } from './button';

interface GymProfile { name: string; description?: string | null; province?: string | null; county?: string | null; city: string; address: string; phone?: string | null; }
export function GymProfileManager({ initial }: { initial: GymProfile }) { const [form, setForm] = useState({ name: initial.name, description: initial.description ?? '', province: initial.province ?? '', county: initial.county ?? '', city: initial.city, address: initial.address }); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); async function save(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(null); setError(null); try { await api.patch('/tenants/me/profile', form); setMessage('اطلاعات عمومی باشگاه ذخیره شد.'); } catch (err) { setError(err instanceof ApiError ? err.message : 'ذخیره انجام نشد.'); } finally { setLoading(false); } } return <MembershipCard><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Input label="نام باشگاه" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><label className="flex flex-col gap-1.5 text-sm text-muted">استان<select className="h-11 rounded-xl border border-border/10 bg-surface px-3 text-ink" value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value, county: '', city: '' })}><option value="">انتخاب استان</option>{IRAN_PROVINCES.map((name) => <option key={name}>{name}</option>)}</select></label><label className="flex flex-col gap-1.5 text-sm text-muted">شهرستان<select className="h-11 rounded-xl border border-border/10 bg-surface px-3 text-ink" value={form.county} onChange={(e) => setForm({ ...form, county: e.target.value, city: e.target.value })}><option value="">انتخاب شهرستان</option>{(IRAN_LOCATIONS[form.province] ?? []).map((name) => <option key={name}>{name}</option>)}</select></label><Input label="شهر / محله" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} required /><Input label="آدرس کامل" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} required /><label className="flex flex-col gap-1.5 text-sm text-muted sm:col-span-2">معرفی باشگاه<textarea className="min-h-32 rounded-xl border border-border/10 bg-surface px-4 py-3 text-ink" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>{message && <p className="text-sm text-success sm:col-span-2">{message}</p>}{error && <p className="text-sm text-danger sm:col-span-2">{error}</p>}<Button type="submit" disabled={loading} className="sm:w-fit">{loading ? 'در حال ذخیره…' : 'ذخیره اطلاعات باشگاه'}</Button></form></MembershipCard>; }
