'use client';

import { useState } from 'react';
import { api } from '../../lib/api';
import { MembershipCard } from './membership-card';
import { Badge } from './badge';
import { Button } from './button';

interface Plan { id: string; code: string; name: string; monthlyPrice: number; features: string[]; }
interface Subscription { id: string; tenantId: string; status: string; renewsAt?: string | null; plan: Plan; tenant: { id: string; name: string; city: string }; }
export function SubscriptionsManager({ plans, initial }: { plans: Plan[]; initial: Subscription[] }) { const [items, setItems] = useState(initial); const [selection, setSelection] = useState<Record<string, string>>({}); async function save(item: Subscription) { const changed = await api.patch<Subscription>(`/super-admin/subscriptions/${item.tenantId}`, { planCode: selection[item.tenantId] ?? item.plan.code, status: item.status === 'SUSPENDED' ? 'ACTIVE' : item.status }); setItems((current) => current.map((value) => value.id === item.id ? changed : value)); } async function toggle(item: Subscription) { const changed = await api.patch<Subscription>(`/super-admin/subscriptions/${item.tenantId}`, { planCode: selection[item.tenantId] ?? item.plan.code, status: item.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' }); setItems((current) => current.map((value) => value.id === item.id ? changed : value)); } return <div className="flex flex-col gap-6"><div className="grid gap-4 md:grid-cols-3">{plans.map((plan) => <MembershipCard key={plan.id}><p className="text-lg font-extrabold">{plan.name}</p><p className="mt-2 text-2xl font-extrabold text-accent-soft">{Number(plan.monthlyPrice).toLocaleString('fa-IR')} <span className="text-xs text-muted">تومان / ماه</span></p><ul className="mt-4 space-y-2 text-sm text-muted">{plan.features.map((feature) => <li key={feature}>• {feature}</li>)}</ul></MembershipCard>)}</div><div className="flex flex-col gap-3">{items.map((item) => <MembershipCard key={item.id} className="flex flex-wrap items-center gap-4"><div className="min-w-48 flex-1"><p className="font-extrabold">{item.tenant.name}</p><p className="mt-1 text-xs text-muted">{item.tenant.city}{item.renewsAt ? ` · تمدید ${new Date(item.renewsAt).toLocaleDateString('fa-IR')}` : ''}</p></div><Badge tone={item.status === 'ACTIVE' ? 'success' : 'warning'}>{item.status === 'ACTIVE' ? 'فعال' : item.status === 'SUSPENDED' ? 'تعلیق' : item.status}</Badge><select className="h-10 rounded-xl border border-border/10 bg-surface px-3 text-sm" value={selection[item.tenantId] ?? item.plan.code} onChange={(event) => setSelection({ ...selection, [item.tenantId]: event.target.value })}>{plans.map((plan) => <option key={plan.code} value={plan.code}>{plan.name}</option>)}</select><Button size="sm" variant="secondary" onClick={() => save(item)}>ذخیره پلن</Button><Button size="sm" variant="ghost" onClick={() => toggle(item)}>{item.status === 'SUSPENDED' ? 'فعال‌سازی' : 'تعلیق'}</Button></MembershipCard>)}</div></div>; }
